# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import agent_pb2 as agent__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RouteTask = channel.unary_unary(
                '/agent.AgentService/RouteTask',
                request_serializer=agent__pb2.RouteRequest.SerializeToString,
                response_deserializer=agent__pb2.Message.FromString,
                _registered_method=True)
        self.PlanTask = channel.unary_unary(
                '/agent.AgentService/PlanTask',
                request_serializer=agent__pb2.PlanRequest.SerializeToString,
                response_deserializer=agent__pb2.Message.FromString,
                _registered_method=True)
        self.ResearchTask = channel.unary_unary(
                '/agent.AgentService/ResearchTask',
                request_serializer=agent__pb2.ResearchRequest.SerializeToString,
                response_deserializer=agent__pb2.Message.FromString,
                _registered_method=True)
        self.ExecuteTask = channel.unary_unary(
                '/agent.AgentService/ExecuteTask',
                request_serializer=agent__pb2.ExecuteRequest.SerializeToString,
                response_deserializer=agent__pb2.Message.FromString,
                _registered_method=True)
        self.SummarizeTask = channel.unary_unary(
                '/agent.AgentService/SummarizeTask',
                request_serializer=agent__pb2.SummarizeRequest.SerializeToString,
                response_deserializer=agent__pb2.Message.FromString,
                _registered_method=True)
        self.VerifyTask = channel.unary_unary(
                '/agent.AgentService/VerifyTask',
                request_serializer=agent__pb2.VerifyRequest.SerializeToString,
                response_deserializer=agent__pb2.Message.FromString,
                _registered_method=True)
        self.ReviewCode = channel.unary_unary(
                '/agent.AgentService/ReviewCode',
                request_serializer=agent__pb2.ReviewRequest.SerializeToString,
                response_deserializer=agent__pb2.Message.FromString,
                _registered_method=True)
        self.DebugCode = channel.unary_unary(
                '/agent.AgentService/DebugCode',
                request_serializer=agent__pb2.DebugRequest.SerializeToString,
                response_deserializer=agent__pb2.Message.FromString,
                _registered_method=True)
        self.ArchiveMemory = channel.unary_unary(
                '/agent.AgentService/ArchiveMemory',
                request_serializer=agent__pb2.ArchiveRequest.SerializeToString,
                response_deserializer=agent__pb2.Message.FromString,
                _registered_method=True)


class AgentServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def RouteTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlanTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResearchTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SummarizeTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReviewCode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DebugCode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ArchiveMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RouteTask': grpc.unary_unary_rpc_method_handler(
                    servicer.RouteTask,
                    request_deserializer=agent__pb2.RouteRequest.FromString,
                    response_serializer=agent__pb2.Message.SerializeToString,
            ),
            'PlanTask': grpc.unary_unary_rpc_method_handler(
                    servicer.PlanTask,
                    request_deserializer=agent__pb2.PlanRequest.FromString,
                    response_serializer=agent__pb2.Message.SerializeToString,
            ),
            'ResearchTask': grpc.unary_unary_rpc_method_handler(
                    servicer.ResearchTask,
                    request_deserializer=agent__pb2.ResearchRequest.FromString,
                    response_serializer=agent__pb2.Message.SerializeToString,
            ),
            'ExecuteTask': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteTask,
                    request_deserializer=agent__pb2.ExecuteRequest.FromString,
                    response_serializer=agent__pb2.Message.SerializeToString,
            ),
            'SummarizeTask': grpc.unary_unary_rpc_method_handler(
                    servicer.SummarizeTask,
                    request_deserializer=agent__pb2.SummarizeRequest.FromString,
                    response_serializer=agent__pb2.Message.SerializeToString,
            ),
            'VerifyTask': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyTask,
                    request_deserializer=agent__pb2.VerifyRequest.FromString,
                    response_serializer=agent__pb2.Message.SerializeToString,
            ),
            'ReviewCode': grpc.unary_unary_rpc_method_handler(
                    servicer.ReviewCode,
                    request_deserializer=agent__pb2.ReviewRequest.FromString,
                    response_serializer=agent__pb2.Message.SerializeToString,
            ),
            'DebugCode': grpc.unary_unary_rpc_method_handler(
                    servicer.DebugCode,
                    request_deserializer=agent__pb2.DebugRequest.FromString,
                    response_serializer=agent__pb2.Message.SerializeToString,
            ),
            'ArchiveMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.ArchiveMemory,
                    request_deserializer=agent__pb2.ArchiveRequest.FromString,
                    response_serializer=agent__pb2.Message.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agent.AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agent.AgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RouteTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AgentService/RouteTask',
            agent__pb2.RouteRequest.SerializeToString,
            agent__pb2.Message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlanTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AgentService/PlanTask',
            agent__pb2.PlanRequest.SerializeToString,
            agent__pb2.Message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResearchTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AgentService/ResearchTask',
            agent__pb2.ResearchRequest.SerializeToString,
            agent__pb2.Message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AgentService/ExecuteTask',
            agent__pb2.ExecuteRequest.SerializeToString,
            agent__pb2.Message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SummarizeTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AgentService/SummarizeTask',
            agent__pb2.SummarizeRequest.SerializeToString,
            agent__pb2.Message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AgentService/VerifyTask',
            agent__pb2.VerifyRequest.SerializeToString,
            agent__pb2.Message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReviewCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AgentService/ReviewCode',
            agent__pb2.ReviewRequest.SerializeToString,
            agent__pb2.Message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DebugCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AgentService/DebugCode',
            agent__pb2.DebugRequest.SerializeToString,
            agent__pb2.Message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ArchiveMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AgentService/ArchiveMemory',
            agent__pb2.ArchiveRequest.SerializeToString,
            agent__pb2.Message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
